package com.jk.universalreview.demoConnector;

import feign.Headers;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@FeignClient(name = "UsersAPI", url = "http://35.224.163.154")
public interface UsersAPI {

    @Headers("Authorization: Bearer eyJraWQiOiJnREhXelcwTWZ4eFFlcFlHWDZMcjNjSDg4M29ScXpUeDkwRWZDTC1oWTg4IiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULkZOejU0VHEyeFhiSFFzWVVmazBjclB6c1VYR1llNGprcW5jN3ZrbmFPeG8ub2FyMms5MWM0YnJEMXdzWTU1ZDciLCJpc3MiOiJodHRwczovL2Rldi03MDU1Nzc5OS5va3RhLmNvbS9vYXV0aDIvZGVmYXVsdCIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE3Mjk3MTQ2MzYsImV4cCI6MTcyOTcxODIzNiwiY2lkIjoiMG9haGd0cnVpYTkzUnZCcng1ZDciLCJ1aWQiOiIwMHVoZ3R0bHM1RkZtZGJ3ejVkNyIsInNjcCI6WyJlbWFpbCIsIm9mZmxpbmVfYWNjZXNzIiwib3BlbmlkIiwicHJvZmlsZSJdLCJhdXRoX3RpbWUiOjE3Mjk3MDcyNjAsInN1YiI6ImFsZXhmYWtlQGF3ZC5jb20ifQ.JWdNFy7R3yJSTXChFey8i52yB3ZICEiNO1jSwNYHNDSNrwZ1Bds15Q-3tcSCzPdfnDtCwVw5sKb7cxhgh2m2Lw0JukO6ZNy1LhzcAOHGMVMrfz6mecpWK3H4l1rOA1X0kr-zGv6poVjhOfavsPNnvr--aheegNJuBXBHS34iL0UprWIl9JbN845pGATLQvAQ_o19FWd2xUXy05aCrADlRG0-6oCdalbZs00S4xclHP0TPnt_a1D7X8nWeMod2pnQE6l3e-JwtOb195jSDAYk0oKmz5kmftn6yJyoefRcMddwjpPwvUqo1aywpVczdutywpqbb_HCPrzwcy-FbXLIZA")
    @RequestMapping(method = RequestMethod.GET, value="/users/list")
    List<User> getUserList();
}
